name: Fork PR Benchmarks (Run)

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  benchmark_fork_pr_branch:
    name: Run Fork PR Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
            toolchain: stable
    
      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo binstall
        uses: taiki-e/install-action@cargo-binstall

      - name: Install gungraun-runner
        run: |
            version=$(cargo metadata --format-version=1 |\
            jq '.packages[] | select(.name == "gungraun").version' |\
            tr -d '"'
            )
            cargo binstall --no-confirm gungraun-runner --version $version --force

      - name: Install Valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Build
        run: cargo build      

      - name: Mock Benchmarking
        run: |
          cargo bench > benchmark_results.txt

      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v5
        with:
          name: benchmark_results.txt
          path: ./benchmark_results.txt

      - name: Upload GitHub Pull Request Event
        uses: actions/upload-artifact@v5
        with:
          name: event.json
          path: ${{ github.event_path }}
